### ISSUE TITLE
Regression with a few models where colors get lost

### ISSUE THREAD

**Issue by hybridherbst** [beersandrew/usd-thumbnail-generator#19]
These models rendered colors before, not anymore:

[BrainStem.glb.blender.usdz.zip](https://github.com/beersandrew/usd-thumbnail-generator/files/12673856/BrainStem.glb.blender.usdz.zip)
<img width="893" alt="image" src="https://github.com/beersandrew/usd-thumbnail-generator/assets/2693840/80fc8499-cda4-4e53-8c2c-3ca6c78d3e7e">

[CesiumMilkTruck.glb.blender.usdz.zip](https://github.com/beersandrew/usd-thumbnail-generator/files/12673864/CesiumMilkTruck.glb.blender.usdz.zip)
<img width="896" alt="image" src="https://github.com/beersandrew/usd-thumbnail-generator/assets/2693840/51ed8fe2-b08a-419b-8eaa-97ce6950eddd">

**Comment by beersandrew** [comment]
resolved with https://github.com/beersandrew/usd-thumbnail-generator/pull/20
